version: '3.8'

services:
  app:
    build: .
    depends_on:
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:RQrmDMCJiBJgZFKujcXBhcONGgUVZNDL@monorail.proxy.rlwy.net:35905/railway
      - REDIS_URL=redis://default:CSYFmhKcOPijusAakuxafCcouViGXfFY@roundhouse.proxy.rlwy.net:25570
    entrypoint: ["./wait-for-postgres.sh", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  redis:
    image: redis:7.2.5
    ports:
      - "6379:6379"