version: '3.8'

services:
  app:
    build: .
    depends_on:
      - redis
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    entrypoint: ["./wait-for-postgres.sh"]

  redis:
    image: redis:7.2.5
    ports:
      - "6379:6379"
